### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by anwebdevelopers** [metinkun/node-binance-api-ext#6]
Why did you abandon support for such a clean and concise library? After all, a lot of work was invested, it is clear that it was written in the image of another repository, but that one became more like a mess ...

**Comment by rishikesh2003** [comment]
Yes, it's a nice library. But looks like he is not maintaining this repository anymore.

**Comment by metinkun** [comment]
hello , i had real life issues. i will continue maintaining. i appreciate any contribution.
